-- ============================================================
-- Migration: Grant SELECT on notification.events to authenticated
-- Date: 2026-04-19
-- ============================================================
-- Gap: notification.events had RLS enabled with a SELECT policy
--      (notification_events_select_own) but no table-level SELECT
--      privilege was granted to the authenticated role.
--
-- Result: inbox controller fetchEventsByIds() received error
--      "permission denied for table events" (42501) when trying to
--      enrich inbox recipient rows with event metadata. The inbox
--      controller caught this and propagated it, causing the
--      notifications screen to throw rather than render.
--
-- Fix: Grant SELECT on notification.events to authenticated.
--      RLS policy notification_events_select_own already ensures
--      users can only see events where they are the source actor
--      or a recipient (via can_access_recipient check).
-- ============================================================

GRANT SELECT ON notification.events TO authenticated;
