// src/utils/idempotency.js
// ============================================================
// Chat Engine — Idempotency Helpers
// ------------------------------------------------------------
// Prevents duplicate operations from being processed twice.
//
// The primary mechanism is client_id on messages:
//   - Generated by the sender before the request
//   - Stored on the message row (unique per conversation)
//   - If a retry arrives with the same client_id, return the
//     existing row instead of inserting a duplicate
// ============================================================

import { getSupabaseClient } from '../config.js'

/**
 * Look up an existing message by client_id + conversation_id.
 *
 * Returns the raw message row if found, null otherwise.
 * Used by sendMessage controller before attempting an insert.
 *
 * @param {Object} params
 * @param {string} params.clientId
 * @param {string} params.conversationId
 * @returns {Promise<Object|null>}
 */
export async function findMessageByClientId({ clientId, conversationId }) {
  if (!clientId || !conversationId) return null

  const supabase = getSupabaseClient()

  const { data, error } = await supabase
    .schema('chat')
    .from('messages')
    .select(`
      id,
      conversation_id,
      sender_actor_id,
      message_kind,
      body,
      reply_to_message_id,
      conversation_seq,
      edited_at,
      deleted_at,
      is_hidden,
      created_at,
      client_id
    `)
    .eq('client_id', clientId)
    .eq('conversation_id', conversationId)
    .maybeSingle()

  if (error) throw error

  return data ?? null
}

/**
 * Generate a stable client_id for a message send attempt.
 *
 * Format: <actorId>:<conversationId>:<timestamp>:<random>
 *
 * @param {Object} params
 * @param {string} params.actorId
 * @param {string} params.conversationId
 * @returns {string}
 */
export function generateClientId({ actorId, conversationId }) {
  const ts = Date.now()
  const rand = Math.random().toString(36).slice(2, 8)
  return `${actorId}:${conversationId}:${ts}:${rand}`
}

