export function mapProviderRow(row) {
  return {
    id:              row.id,
    actorId:         row.actor_id,
    name:            row.name,
    avatarUrl:       row.avatar_url,
    bannerUrl:       row.banner_url ?? "",
    logoUrl:         row.logo_url ?? "",
    phonePublic:     row.phone_public,
    email:           row.email ?? "",
    websiteUrl:      row.website_url ?? "",
    addressText:     row.address_text ?? "",
    googleMapsUrl:   row.google_maps_url ?? "",
    instagramUrl:    row.instagram_url ?? "",
    facebookUrl:     row.facebook_url ?? "",
    categoryKey:     row.category_key,
    citySlug:        row.city_slug,
    cityName:        row.city_name ?? "",
    city:            row.city,
    stateCode:       row.state_code ?? "",
    countryCode:     row.country_code,
    zipCode:         row.zip_code ?? "",
    directoryVisible: row.directory_visible,
    directoryStatus: row.directory_status,
    hours:           row.hours,
    description:     row.description ?? "",
    priceNotes:      row.price_notes ?? "",
    sourceUrl:       row.source_url ?? "",
    notes:           row.notes ?? "",
    bookingUrl:      row.booking_url,
    createdAt:       row.created_at,
    updatedAt:       row.updated_at,
    source:          row.source ?? "vport",
    sourceLabel:     row.source_label ?? "Traffic provider",
    intakeId:        row.intake_id ?? null,
    hasAvatar:  Boolean(row.avatar_url),
    hasPhone:   Boolean(row.phone_public),
    hasHours:   Boolean(row.hours),
    hasBooking: Boolean(row.booking_url),
    hasCity:    Boolean(row.city_slug || row.city),
    hasService: Boolean(row.category_key),
    isClaimed:  Boolean(row.actor_id),
    isActive:   Boolean(row.directory_visible) && row.directory_status === "listed",
    isImportedIntake: row.source === "traffic_intake",
  };
}
