const fs                      = require('fs')
const crypto                  = require('crypto')
const { execFileSync, execSync } = require('child_process')
const { scanSwiftFiles }      = require('./scanSwiftFiles')
const { buildNativeGraph }    = require('./buildNativeGraph')
const { writeNativeGraph }    = require('./writeNativeGraph')

const NOW = new Date().toISOString()
const NATIVE_ROOT = '/Users/vcsm/Documents/New project/native'

function getGitInfo() {
  try {
    const branch = runGit(['rev-parse', '--abbrev-ref', 'HEAD'])
    const commit = runGit(['rev-parse', '--short', 'HEAD'])
    const status = execSync(`git -C "${NATIVE_ROOT}" status --porcelain 2>/dev/null || true`, { encoding: 'utf8' }).trim()
    return { branch, commit, dirty: status.length > 0 }
  } catch {
    return { branch: 'unknown', commit: 'unknown', dirty: false }
  }
}

function runGit(args) {
  try {
    const value = execFileSync('git', ['-C', NATIVE_ROOT, ...args], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim()
    return value || 'unknown'
  } catch {
    return 'unknown'
  }
}

function computeSourceHash(files) {
  const hash = crypto.createHash('sha256')

  for (const file of files) {
    hash.update(file)
    hash.update('\0')
    hash.update(fs.readFileSync(file))
    hash.update('\0')
  }

  return hash.digest('hex')
}

function validate(graph) {
  const errors = []

  if (!graph.nodes || graph.nodes.length === 0) {
    errors.push('Graph has zero nodes')
  }

  const ids = new Set()
  for (const node of (graph.nodes || [])) {
    if (ids.has(node.id)) errors.push(`Duplicate node id: ${node.id}`)
    ids.add(node.id)
  }

  for (const edge of (graph.edges || [])) {
    if (!ids.has(edge.source)) errors.push(`Edge source missing: ${edge.source}`)
    if (!ids.has(edge.target)) errors.push(`Edge target missing: ${edge.target}`)
  }

  return errors
}

async function main() {
  console.log('native-graph-codegen — Swift source scan')
  console.log('─'.repeat(50))

  // ── Phase 1: Scan ──────────────────────────────────────────────────────────
  process.stdout.write('scanning Swift files... ')
  const files = await scanSwiftFiles()
  console.log(`${files.length} found`)

  // ── Phase 2: Build graph ───────────────────────────────────────────────────
  process.stdout.write('building native graph... ')
  const { nodes, edges, allTables } = buildNativeGraph(files)
  console.log(`${nodes.length} nodes, ${edges.length} edges`)

  // ── Phase 3: Validate ──────────────────────────────────────────────────────
  const graph = assembleGraph(nodes, edges, allTables, files)
  const errors = validate(graph)
  if (errors.length > 0) {
    console.error('\nGraph validation failed:')
    for (const e of errors) console.error(`  ✗ ${e}`)
    process.exit(1)
  }
  console.log('validation passed')

  // ── Phase 4: Write ─────────────────────────────────────────────────────────
  console.log('writing...')
  writeNativeGraph(graph, 'native-bottom-navigation')

  // ── Summary ────────────────────────────────────────────────────────────────
  const layerCounts = {}
  for (const node of nodes) {
    const l = node.data.layer
    layerCounts[l] = (layerCounts[l] || 0) + 1
  }

  console.log('─'.repeat(50))
  console.log('Native graph synced')
  console.log(`Files scanned:  ${files.length}`)
  console.log(`Nodes:          ${nodes.length}`)
  console.log(`Edges:          ${edges.length}`)
  console.log(`DB Tables:      ${allTables.length}`)
  console.log()
  console.log('layer breakdown:')
  for (const [layer, count] of Object.entries(layerCounts).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${layer.padEnd(14)} ${count}`)
  }
  console.log()
  console.log('done.')
}

function assembleGraph(nodes, edges, allTables, files) {
  const git = getGitInfo()
  const sourceHash = computeSourceHash(files)

  const layerCounts = {}
  for (const node of nodes) {
    const l = node.data.layer
    layerCounts[l] = (layerCounts[l] || 0) + 1
  }

  return {
    metadata: {
      graph:       'native-bottom-navigation',
      title:       'Native Bottom Navigation Runtime',
      name:        'Native App',
      version:     '1.0.0',
      generatedBy: 'native-graph-codegen',
      generatedAt: NOW,
      scope:       'VCSMNativeApp',
      graphType:   'native-runtime',
      confidence:  'STATICALLY_TRACED',
      nativeRoot:  NATIVE_ROOT,
      filesScanned: files.length,
      sourceHash,
      gitBranch:   git.branch,
      gitCommit:   git.commit,
      dirty:       git.dirty,
      stats: {
        filesScanned: files.length,
        nodes:          nodes.length,
        edges:          edges.length,
        dbTables:       allTables.length,
        layerBreakdown: layerCounts,
      },
      dbTables: allTables,
      notes: 'Auto-generated by native-graph-codegen from static Swift source analysis. Regex-based — not full AST. Edges inferred from feature-folder co-location and DAL table references.',
    },
    nodes,
    edges,
  }
}

main().catch((err) => {
  console.error('\nnative-graph-codegen failed:', err.message)
  console.error(err.stack)
  process.exit(1)
})
