import fs from "node:fs/promises";
import path from "node:path";
import { pathExists } from "../core/fs.js";

export async function writeScreensReport(config, screenMap) {
  const byFeature = groupByFeature(screenMap.screens);
  const featureDocsRoot = path.join(config.docsRoot, "features");

  await Promise.all(
    [...byFeature.entries()].map(([feature, screens]) =>
      writeFeatureScreens(featureDocsRoot, feature, screens, config)
    )
  );
}

async function writeFeatureScreens(featureDocsRoot, feature, screens, config) {
  const featureDir = path.join(featureDocsRoot, feature);
  if (!(await pathExists(featureDir))) return;

  const content = renderScreensDoc(feature, screens, config);
  await fs.writeFile(path.join(featureDir, "SCREENS.md"), content, "utf8");
}

function renderScreensDoc(feature, screens, config) {
  const linked = screens.filter((s) => s.routes.length > 0);
  const unlinked = screens.filter((s) => s.routes.length === 0);
  const finalScreens = linked.filter((s) => s.screenKind === "final-screen");
  const viewScreens = screens.filter((s) => s.screenKind === "view-screen");
  const unknownScreens = screens.filter((s) => s.screenKind === "unknown-screen");

  return `# Screens — ${feature}

*Generated by scanner ${config.scannerVersion} on ${new Date().toISOString()}*

## Summary

| | Count |
|---|---|
| Total screens | ${screens.length} |
| Route-linked | ${linked.length} |
| — final-screen | ${finalScreens.length} |
| — view-screen (linked) | ${linked.filter((s) => s.screenKind === "view-screen").length} |
| Unlinked view-screen | ${unlinked.filter((s) => s.screenKind === "view-screen").length} |
| unknown-screen | ${unknownScreens.length} |

## Route-Linked Screens

${linked.length === 0 ? "_None found._" : routeLinkedTable(linked)}

## Unlinked Screens

${unlinked.filter((s) => s.screenKind !== "unknown-screen").length === 0 && unknownScreens.filter((s) => s.routes.length === 0).length === 0 ? "_None found._" : unlinkedTable(unlinked)}
`;
}

function routeLinkedTable(screens) {
  const rows = screens
    .sort((a, b) => a.component.localeCompare(b.component))
    .map((s) => `| \`${s.component}\` | ${s.screenKind} | ${s.routes.map((r) => `\`${r}\``).join(", ")} | ${s.access} | ${s.confidence} |`);

  return `| Component | Kind | Routes | Access | Confidence |
|---|---|---|---|---|
${rows.join("\n")}`;
}

function unlinkedTable(screens) {
  if (screens.length === 0) return "_None found._";
  const rows = screens
    .sort((a, b) => a.component.localeCompare(b.component))
    .map((s) => `| \`${s.component}\` | ${s.screenKind} | ${s.file} | ${s.confidence} |`);

  return `| Component | Kind | File | Confidence |
|---|---|---|---|
${rows.join("\n")}`;
}

function groupByFeature(screens) {
  const map = new Map();
  for (const screen of screens) {
    if (!screen.feature || screen.appId !== "VCSM") continue;
    if (!map.has(screen.feature)) map.set(screen.feature, []);
    map.get(screen.feature).push(screen);
  }
  return map;
}
