import path from "node:path";
import { writeJson } from "../core/fs.js";
import fs from "node:fs/promises";

export async function writeFeatureImportMap(config, featureImportMap) {
  const outputDir = path.join(config.docsRoot, "ARCHITECTURETICKETING");
  const jsonPath = path.join(outputDir, "FEATURE_IMPORT_MAP.json");
  const mdPath = path.join(outputDir, "FEATURE_IMPORT_MAP.md");

  await fs.mkdir(outputDir, { recursive: true });
  await writeJson(jsonPath, featureImportMap);
  await fs.writeFile(mdPath, buildMarkdown(featureImportMap), "utf8");

  return { jsonPath, mdPath };
}

function buildMarkdown(map) {
  const lines = [];
  const { features, total_violations, bidir_pairs, split_candidates, generated } = map;

  lines.push("# Feature Import Map");
  lines.push("");
  lines.push(`**Generated:** ${generated}  `);
  lines.push(`**Source dependency-map:** \`apps/scanner/maps/dependency-map.json\`  `);
  lines.push(`**Source feature-map:** \`apps/scanner/maps/feature-map.json\`  `);
  lines.push(`**Features scanned:** ${map.feature_count}  `);
  lines.push(`**Total boundary violations:** ${total_violations}  `);
  lines.push(`**Bidirectional pairs:** ${bidir_pairs.length}  `);
  lines.push(`**Split candidates:** ${split_candidates.length}  `);
  lines.push("");

  // Executive Summary
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(
    `This map was generated by the VCSM feature import map scanner as part of ARCH-IMPORTMAP-001. ` +
    `It reshapes the scanner's existing \`dependency-map.json\` and \`feature-map.json\` outputs into a ` +
    `per-feature governance format, classifying each cross-feature import against the adapter boundary rules.`
  );
  lines.push("");
  lines.push(`**${map.feature_count}** VCSM features scanned across **${countEdges(features)}** cross-feature dependency edges.`);
  lines.push("");

  const ruleBreakdown = buildRuleBreakdown(features);
  if (Object.keys(ruleBreakdown).length > 0) {
    lines.push("Rule firing breakdown:");
    lines.push("");
    for (const [rule, count] of Object.entries(ruleBreakdown)) {
      lines.push(`- \`${rule}\`: ${count} firings`);
    }
    lines.push("");
  }

  // Feature Summary Table
  lines.push("## Feature Summary Table");
  lines.push("");
  lines.push("| Feature | Files | Inbound | Outbound | Violations | Split Candidate |");
  lines.push("|---|---|---|---|---|---|");
  for (const f of features) {
    const violationCount = f.violations.length;
    lines.push(
      `| ${f.name} | ${f.file_count} | ${f.inbound.length} | ${f.outbound.length} | ${violationCount} | ${f.split_candidate ? "YES" : "no"} |`
    );
  }
  lines.push("");

  // Boundary Violations
  lines.push("## Boundary Violations");
  lines.push("");

  const allViolations = features.flatMap((f) => f.violations);
  if (allViolations.length === 0) {
    lines.push("_No boundary violations detected._");
  } else {
    lines.push("| Rule | From | To | File | Import |");
    lines.push("|---|---|---|---|---|");
    for (const v of allViolations) {
      const fromFile = v.from_file ? v.from_file.split("/").slice(-2).join("/") : "—";
      const importShort = v.import_path ? v.import_path.slice(0, 80) : "—";
      lines.push(`| \`${v.rule}\` | ${v.from_feature} | ${v.to_feature} | \`${fromFile}\` | \`${importShort}\` |`);
    }
  }
  lines.push("");

  // Bidirectional Pairs
  lines.push("## Bidirectional Pairs");
  lines.push("");
  lines.push(
    `Bidirectional dependency pairs are flagged for classification only. ` +
    `No direction decisions are made here — see ARCH-BIDIR-001.`
  );
  lines.push("");
  if (bidir_pairs.length === 0) {
    lines.push("_No bidirectional pairs detected._");
  } else {
    lines.push(`**${bidir_pairs.length} bidirectional pairs detected:**`);
    lines.push("");
    bidir_pairs.forEach((pair, i) => {
      lines.push(`${i + 1}. \`${pair.a}\` ↔ \`${pair.b}\``);
    });
  }
  lines.push("");

  // Split Candidates
  lines.push("## Split Candidates");
  lines.push("");
  lines.push(`Features with more than ${100} files are flagged as split candidates.`);
  lines.push("");
  const splitFeatures = features.filter((f) => f.split_candidate);
  if (splitFeatures.length === 0) {
    lines.push("_No split candidates detected._");
  } else {
    lines.push("| Feature | Files | Split Reason |");
    lines.push("|---|---|---|");
    for (const f of splitFeatures) {
      lines.push(`| ${f.name} | ${f.file_count} | ${f.split_reason} |`);
    }
  }
  lines.push("");

  // Scanner Source
  lines.push("## Scanner Source");
  lines.push("");
  lines.push("This report is generated by a post-processor scanner, not from AST re-parsing.");
  lines.push("The underlying import data is sourced from:");
  lines.push("");
  lines.push("- **`dependency-map.json`** — 380 total dependency edges across all apps, 106 VCSM feature→feature edges");
  lines.push("- **`feature-map.json`** — 69 total features across all apps, 34 VCSM features");
  lines.push("");
  lines.push("The scanner that generates these maps is `apps/scanner/src/scanners/dependencyScanner.js`");
  lines.push("and `apps/scanner/src/scanners/featureScanner.js`. The post-processor is");
  lines.push("`apps/scanner/src/scanners/featureImportMapScanner.js`.");
  lines.push("");

  // Final Verdict
  lines.push("## Final Verdict");
  lines.push("");

  const criticalPairs = bidir_pairs.filter((p) =>
    (p.a === "dashboard" && p.b === "profiles") ||
    (p.a === "profiles" && p.b === "dashboard")
  );

  if (total_violations === 0) {
    lines.push("**No boundary violations detected.** All cross-feature imports go through adapter boundaries.");
  } else {
    lines.push(`**${total_violations} boundary violations detected across ${map.feature_count} features.**`);
    lines.push("");
    lines.push("Critical findings:");
    lines.push("");

    const dashProfileViolations = features
      .find((f) => f.name === "dashboard")
      ?.violations.filter((v) => v.to_feature === "profiles") ?? [];
    const profilesBookingViolations = features
      .find((f) => f.name === "profiles")
      ?.violations.filter((v) => v.to_feature === "booking") ?? [];

    if (dashProfileViolations.length > 0) {
      lines.push(
        `- **dashboard → profiles:** ${new Set(dashProfileViolations.map(v => v.from_file + v.import_path)).size} imports violate adapter boundaries — ` +
        `direct access into \`profiles/kinds/vport/controller\` and \`profiles/kinds/vport/dal\`. ` +
        `Must be resolved before ARCH-DASH-001 implementation.`
      );
    }
    if (profilesBookingViolations.length > 0) {
      lines.push(
        `- **profiles → booking:** ${new Set(profilesBookingViolations.map(v => v.from_file + v.import_path)).size} imports violate adapter boundaries — ` +
        `direct access into \`booking/model\`. ` +
        `Must be resolved before ARCH-VPORTPROFILE-001 implementation.`
      );
    }
    lines.push("");
    lines.push("All violations require remediation strategy (Option A: expose via adapter; Option B: move with feature)");
    lines.push("before any split implementation ticket is opened. See ARCH-DASH-001 and ARCH-VPORTPROFILE-001.");
  }
  lines.push("");

  return lines.join("\n");
}

function countEdges(features) {
  const seen = new Set();
  for (const f of features) {
    for (const o of f.outbound) {
      seen.add(`${f.name}→${o.to_feature}`);
    }
  }
  return seen.size;
}

function buildRuleBreakdown(features) {
  const counts = {};
  for (const f of features) {
    for (const v of f.violations) {
      counts[v.rule] = (counts[v.rule] ?? 0) + 1;
    }
  }
  return counts;
}
