export function mapIntakeLeadRow(row, { cityMap = new Map(), serviceMap = new Map() } = {}) {
  const city    = cityMap.get(row.city_id);
  const service = serviceMap.get(row.service_id);
  return {
    id:                 row.id,
    businessName:       row.business_name,
    businessType:       row.business_type        ?? "",
    slug:               row.slug                 ?? "",
    description:        row.description          ?? "",
    serviceId:          row.service_id           ?? "",
    serviceName:        service?.name            ?? "—",
    serviceCategory:    service?.category        ?? "",
    cityId:             row.city_id              ?? "",
    cityName:           row.city_name ?? city?.name ?? "—",
    citySlug:           row.city_slug            ?? "",
    neighborhoodId:     row.neighborhood_id      ?? "",
    countryCode:        row.country_code         ?? "",
    stateCode:          row.state_code           ?? "",
    zipCode:            row.zip_code             ?? row.postal_code ?? "",
    phone:              row.phone                ?? "",
    email:              row.email                ?? "",
    websiteUrl:         row.website_url          ?? "",
    addressText:        row.address_text         ?? "",
    lat:                row.lat                  ?? "",
    lng:                row.lng                  ?? "",
    hours:              row.hours                ?? null,
    avatarUrl:          row.avatar_url           ?? "",
    bannerUrl:          row.banner_url           ?? "",
    logoUrl:            row.logo_url             ?? "",
    googleMapsUrl:      row.google_maps_url      ?? "",
    instagramUrl:       row.instagram_url        ?? "",
    facebookUrl:        row.facebook_url         ?? "",
    priceNotes:         row.price_notes          ?? "",
    sourceUrl:          row.source_url           ?? "",
    notes:              row.notes                ?? "",
    status:             row.status               ?? "draft",
    source:             row.source               ?? "manual_dashboard",
    importedProviderId: row.imported_provider_id ?? null,
    reviewedAt:         row.reviewed_at          ?? null,
    createdAt:          row.created_at,
    hasLatLng:  Boolean(row.lat) && Boolean(row.lng),
    hasPhone:   Boolean(row.phone),
    hasService: Boolean(row.service_id),
    hasCity:    Boolean(row.city_id) || Boolean(row.city_name),
    hasCountry: Boolean(row.country_code) || Boolean(row.city_id),
    canPublish: Boolean(row.city_id) || (Boolean(row.city_name) && Boolean(row.country_code)),
    isImported: row.status === "imported",
  };
}

export function mapTrazeProviderRow(row) {
  return {
    id:               row.id,
    displayName:      row.display_name,
    slug:             row.slug               ?? "",
    businessType:     row.business_type      ?? "",
    shortBio:         row.short_bio          ?? "",
    cityId:           row.primary_city_id    ?? "",
    serviceId:        row.primary_service_id ?? "",
    phone:            row.phone              ?? "",
    email:            row.email              ?? "",
    websiteUrl:       row.website_url        ?? "",
    addressText:      row.address_text       ?? "",
    lat:              row.lat                ?? "",
    lng:              row.lng                ?? "",
    hours:            row.hours              ?? null,
    avatarUrl:        row.avatar_url         ?? "",
    bannerUrl:        row.banner_url         ?? "",
    logoUrl:          row.logo_url           ?? "",
    googleMapsUrl:    row.google_maps_url    ?? "",
    instagramUrl:     row.instagram_url      ?? "",
    facebookUrl:      row.facebook_url       ?? "",
    platformProfileUrl: row.platform_profile_url ?? "",
    claimStatus:      row.claim_status,
    isActive:         row.is_active,
    isIndexable:      row.is_indexable,
    sourceLeadId:     row.source_provider_id ?? null,
    createdAt:        row.created_at,
    updatedAt:        row.updated_at,
  };
}

export function mapClaimRequestRow(row) {
  return {
    id:                 row.id,
    providerId:         row.provider_id       ?? null,
    providerSlug:       row.provider_slug,
    businessName:       row.business_name     ?? row.provider_slug,
    ownerName:          row.owner_name,
    role:               row.role,
    contactMethod:      row.contact_method,
    phone:              row.phone             ?? "",
    email:              row.email             ?? "",
    verificationMethod: row.verification_method,
    verificationStatus: row.verification_status,
    claimStatus:        row.claim_status,
    claimConfidence:    row.claim_confidence,
    instagramUrl:       row.instagram_url     ?? "",
    websiteUrl:         row.website_url       ?? "",
    notes:              row.notes             ?? "",
    proofImageUrl:      row.proof_image_url   ?? "",
    source:             row.source,
    reviewedAt:         row.reviewed_at       ?? null,
    createdAt:          row.created_at,
  };
}
