name = "upload-worker"
main = "src/index.js" 
compatibility_date = "2025-07-02"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "post-media" 
preview_bucket_name = "post-media"

[vars]
R2_PUBLIC_DOMAIN = "https://cdn.vibezcitizens.com"