name = "upload-worker"
main = "worker.js"
compatibility_date = "2025-07-02"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "vibezcitizens"
preview_bucket_name = "vibezcitizens"

[vars]
R2_PUBLIC_DOMAIN = "https://cdn.vibezcitizens.com" 
