const { scanFiles }           = require('./scanFiles')
const { parseFile }           = require('./parseFile')
const { extractImports }      = require('./extractImports')
const { extractSupabaseReads} = require('./extractSupabaseReads')
const { buildGraph }          = require('./buildGraph')
const { writeGraph }          = require('./writeGraph')

const NOW = new Date().toISOString().split('T')[0]

async function main() {
  const args           = process.argv.slice(2)
  const withVisualizer = args.includes('--visualizer')

  console.log('SHIELD graph-codegen — source-imports pass')
  console.log('─'.repeat(50))

  // ── Phase 1: Scan ────────────────────────────────────────────────────────────
  process.stdout.write('scanning files... ')
  const files = await scanFiles()
  console.log(`${files.length} found`)

  // ── Phase 2: Parse + extract ─────────────────────────────────────────────────
  process.stdout.write('parsing... ')
  const fileDataList = []
  let importCount  = 0
  let parseErrors  = 0
  let tableCount   = 0

  for (const filePath of files) {
    try {
      const ast           = parseFile(filePath)
      const imports       = extractImports(ast)
      const { tables, rpcs } = extractSupabaseReads(ast)
      importCount += imports.length
      tableCount  += tables.length
      fileDataList.push({ filePath, imports, tables, rpcs })
    } catch {
      parseErrors++
      fileDataList.push({ filePath, imports: [], tables: [], rpcs: [] })
    }
  }
  console.log(`done (${importCount} imports, ${tableCount} supabase calls, ${parseErrors} errors)`)

  // ── Phase 3: Build graph ─────────────────────────────────────────────────────
  process.stdout.write('building graph... ')
  const { nodes, edges } = buildGraph(fileDataList)
  console.log(`${nodes.length} nodes, ${edges.length} edges`)

  // ── Phase 4: Collect stats ───────────────────────────────────────────────────
  const layerCounts = {}
  for (const node of nodes) {
    const l = node.data.layer
    layerCounts[l] = (layerCounts[l] || 0) + 1
  }

  const allTables = [...new Set(fileDataList.flatMap(f => f.tables))]

  // ── Phase 5: Assemble graph JSON ─────────────────────────────────────────────
  const graph = {
    metadata: {
      graph:       'source-imports',
      title:       'VCSM — Source Import Graph',
      name:        'Source Imports',
      version:     '1.0.0',
      generatedBy: 'graph-codegen',
      generatedAt: NOW,
      scope:       'VCSM',
      graphType:   'source-imports',
      confidence:  'STATICALLY_TRACED',
      stats: {
        filesScanned:    files.length,
        parseErrors,
        nodes:           nodes.length,
        edges:           edges.length,
        supabaseTables:  allTables.length,
        layerBreakdown:  layerCounts,
      },
      supabaseTables: allTables.sort(),
      notes: [
        'Auto-generated by graph-codegen from static import analysis.',
        'Positions: layered left→right by architecture role (dal → engine → controller → hook → screen → route).',
        'Engine nodes are synthetic — created from detected @alias imports.',
        'Confidence is STATICALLY_TRACED for all file nodes and resolved internal edges.',
      ].join(' '),
    },
    nodes,
    edges,
  }

  // ── Phase 6: Write ───────────────────────────────────────────────────────────
  console.log('writing...')
  writeGraph(graph, { visualizer: withVisualizer })

  // ── Summary ──────────────────────────────────────────────────────────────────
  console.log('─'.repeat(50))
  console.log('layer breakdown:')
  for (const [layer, count] of Object.entries(layerCounts).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${layer.padEnd(12)} ${count}`)
  }
  console.log(`\nsupabase tables (${allTables.length}):`)
  allTables.sort().forEach(t => console.log(`  ${t}`))
  console.log('\ndone.')
}

main().catch((err) => {
  console.error('\ngraph-codegen failed:', err.message)
  console.error(err.stack)
  process.exit(1)
})
