import React, { useEffect, useState } from "react";
import { supabase } from "@/services/supabase/supabaseClient";
import { createStudent } from "@/features/services/supabase/createStudent";

const PRIMARY = "#0f4a72";
const MUTED = "#64748b";
const BORDER = "#e2e8f0";
const SURFACE = "#f8fafc";

const inputStyle = {
  width: "100%", padding: "10px 12px", borderRadius: 10,
  border: `1px solid ${BORDER}`, fontSize: 14,
  background: "#fff", color: "#0f172a", boxSizing: "border-box",
};

const STEPS = ["Student Information", "Guardian Information", "School Account", "Enrollment"];

const GRADE_LEVELS = [
  "Pre-K", "Kindergarten",
  "1st Grade", "2nd Grade", "3rd Grade", "4th Grade", "5th Grade", "6th Grade",
  "7th Grade", "8th Grade", "9th Grade", "10th Grade", "11th Grade", "12th Grade",
];

const GENDERS = ["Male", "Female", "Non-binary", "Prefer not to say"];

const RELATIONSHIPS = [
  "Mother", "Father", "Stepmother", "Stepfather",
  "Grandmother", "Grandfather", "Aunt", "Uncle",
  "Legal Guardian", "Foster Parent", "Other",
];

function Field({ label, required, children, help }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
      <label style={{ fontSize: 13, fontWeight: 600, color: "#0f172a" }}>
        {label}{required && <span style={{ color: "#dc2626" }}> *</span>}
      </label>
      {children}
      {help && <span style={{ fontSize: 12, color: MUTED }}>{help}</span>}
    </div>
  );
}

function FieldRow({ children }) {
  return (
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
      {children}
    </div>
  );
}

function StepIndicator({ steps, current }) {
  return (
    <div style={{ display: "flex", gap: 4, marginBottom: 8 }}>
      {steps.map((label, i) => (
        <div key={label} style={{ flex: 1, display: "flex", flexDirection: "column", gap: 4 }}>
          <div style={{
            height: 3, borderRadius: 2,
            background: i <= current ? PRIMARY : BORDER,
            transition: "background 0.2s",
          }} />
          <span style={{
            fontSize: 11, fontWeight: i === current ? 700 : 400,
            color: i <= current ? PRIMARY : MUTED,
          }}>
            {label}
          </span>
        </div>
      ))}
    </div>
  );
}

function SectionTitle({ children }) {
  return (
    <h4 style={{ margin: "4px 0 0", fontSize: 15, fontWeight: 700, color: "#0f172a" }}>
      {children}
    </h4>
  );
}

export default function RegisterStudentModal({ organizationId, onClose, onSuccess }) {
  const [step, setStep] = useState(0);

  // Step 1: Student Info
  const [firstName, setFirstName] = useState("");
  const [middleName, setMiddleName] = useState("");
  const [lastName, setLastName] = useState("");
  const [secondLastName, setSecondLastName] = useState("");
  const [preferredName, setPreferredName] = useState("");
  const [dateOfBirth, setDateOfBirth] = useState("");
  const [gender, setGender] = useState("");
  const [gradeLevel, setGradeLevel] = useState("");
  const [section, setSection] = useState("");

  // Step 2: Guardian Info
  const [guardianFirstName, setGuardianFirstName] = useState("");
  const [guardianLastName, setGuardianLastName] = useState("");
  const [relationship, setRelationship] = useState("");
  const [guardianEmail, setGuardianEmail] = useState("");
  const [guardianPhone, setGuardianPhone] = useState("");

  // Step 3: School Account (read-only preview)
  // login_id and password are auto-generated by the backend

  // Step 4: Enrollment
  const [courses, setCourses] = useState([]);
  const [selectedCourseIds, setSelectedCourseIds] = useState(new Set());
  const [loadingCourses, setLoadingCourses] = useState(true);

  // Shared
  const [saving, setSaving] = useState(false);
  const [feedback, setFeedback] = useState(null);

  useEffect(() => {
    if (!organizationId) return;
    supabase.schema("learning").from("courses")
      .select("id, title, status")
      .eq("organization_id", organizationId)
      .in("status", ["published", "active", "draft"])
      .order("title")
      .then(({ data }) => {
        setCourses(data ?? []);
        setLoadingCourses(false);
      });
  }, [organizationId]);

  function toggleCourse(id) {
    setSelectedCourseIds(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  }

  function buildFullName() {
    return [firstName, middleName, lastName, secondLastName]
      .map(s => s.trim())
      .filter(Boolean)
      .join(" ");
  }

  function buildGuardianName() {
    return [guardianFirstName, guardianLastName]
      .map(s => s.trim())
      .filter(Boolean)
      .join(" ");
  }

  const canAdvanceStep0 = firstName.trim() && lastName.trim() && gradeLevel;
  const canAdvanceStep1 = guardianFirstName.trim() && guardianLastName.trim() && relationship && guardianEmail.trim();
  const canAdvanceStep2 = true; // auto-generated
  const canSubmit = canAdvanceStep0 && canAdvanceStep1 && selectedCourseIds.size > 0 && !saving;

  function nextStep() {
    if (step < STEPS.length - 1) setStep(step + 1);
  }
  function prevStep() {
    if (step > 0) setStep(step - 1);
  }

  async function handleSubmit(e) {
    e.preventDefault();
    if (!canSubmit) return;

    setSaving(true);
    setFeedback(null);

    try {
      const res = await createStudent({
        organizationId,
        courseIds: [...selectedCourseIds],
        displayName: buildFullName(),
        parentName: buildGuardianName(),
        parentEmail: guardianEmail.trim(),
      });

      if (!res.ok) {
        setSaving(false);
        setFeedback({ ok: false, message: res.error?.message ?? "Registration failed." });
        return;
      }

      const d = res.data;
      let msg = `${buildFullName()} has been registered successfully.`;
      msg += `\n\nStudent ID: ${d.loginId}`;
      msg += `\nTemporary Password: ${d.generatedPassword}`;
      msg += `\nCourses Enrolled: ${d.enrolledCourses}`;
      msg += `\n\nThe student must change their password on first login.`;
      if (guardianEmail.trim()) msg += `\nGuardian contact: ${guardianEmail.trim()}`;

      setFeedback({ ok: true, message: msg });
      onSuccess?.();
    } catch (err) {
      setFeedback({ ok: false, message: err?.message ?? "Unexpected error." });
    } finally {
      setSaving(false);
    }
  }

  return (
    <div
      style={{
        position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)",
        display: "flex", alignItems: "center", justifyContent: "center",
        zIndex: 1000, padding: 16,
      }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        style={{
          background: "#fff", borderRadius: 16, width: "100%", maxWidth: 620,
          maxHeight: "92vh", display: "flex", flexDirection: "column",
          boxShadow: "0 12px 40px rgba(0,0,0,0.22)",
        }}
        role="dialog" aria-modal="true" aria-label="Register Student"
      >
        {/* Header */}
        <div style={{ padding: "24px 28px 0", display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
          <div>
            <span style={{ fontSize: 11, fontWeight: 700, color: PRIMARY, textTransform: "uppercase", letterSpacing: 1 }}>
              Student Registration
            </span>
            <h3 style={{ margin: "4px 0 0", fontSize: 20, fontWeight: 800, color: "#0f172a" }}>
              Register New Student
            </h3>
          </div>
          <button onClick={onClose} aria-label="Close" style={{
            background: "none", border: "none", cursor: "pointer",
            color: MUTED, fontSize: 22, padding: 4, lineHeight: 1,
          }}>✕</button>
        </div>

        {/* Step indicator */}
        <div style={{ padding: "16px 28px 0" }}>
          <StepIndicator steps={STEPS} current={step} />
        </div>

        {/* Body */}
        <div style={{ padding: "16px 28px 24px", overflowY: "auto", flex: 1 }}>
          <form id="register-student-form" onSubmit={handleSubmit}>

            {/* ── Step 0: Student Information ─────────────────── */}
            {step === 0 && (
              <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
                <SectionTitle>Student Information</SectionTitle>

                <FieldRow>
                  <Field label="First Name" required>
                    <input type="text" value={firstName} onChange={e => setFirstName(e.target.value)} placeholder="e.g. Juan" required style={inputStyle} />
                  </Field>
                  <Field label="Middle Name">
                    <input type="text" value={middleName} onChange={e => setMiddleName(e.target.value)} placeholder="e.g. Carlos" style={inputStyle} />
                  </Field>
                </FieldRow>

                <FieldRow>
                  <Field label="Last Name" required>
                    <input type="text" value={lastName} onChange={e => setLastName(e.target.value)} placeholder="e.g. Rodriguez" required style={inputStyle} />
                  </Field>
                  <Field label="Second Last Name">
                    <input type="text" value={secondLastName} onChange={e => setSecondLastName(e.target.value)} placeholder="e.g. Martinez" style={inputStyle} />
                  </Field>
                </FieldRow>

                <Field label="Preferred Name" help="What the student prefers to be called in class.">
                  <input type="text" value={preferredName} onChange={e => setPreferredName(e.target.value)} placeholder="e.g. Juanito" style={inputStyle} />
                </Field>

                <FieldRow>
                  <Field label="Date of Birth">
                    <input type="date" value={dateOfBirth} onChange={e => setDateOfBirth(e.target.value)} style={inputStyle} />
                  </Field>
                  <Field label="Gender">
                    <select value={gender} onChange={e => setGender(e.target.value)} style={inputStyle}>
                      <option value="">Select...</option>
                      {GENDERS.map(g => <option key={g} value={g}>{g}</option>)}
                    </select>
                  </Field>
                </FieldRow>

                <FieldRow>
                  <Field label="Grade Level" required>
                    <select value={gradeLevel} onChange={e => setGradeLevel(e.target.value)} required style={inputStyle}>
                      <option value="">Select grade...</option>
                      {GRADE_LEVELS.map(g => <option key={g} value={g}>{g}</option>)}
                    </select>
                  </Field>
                  <Field label="Section / Group" help="e.g. Section A, Group 3">
                    <input type="text" value={section} onChange={e => setSection(e.target.value)} placeholder="e.g. Section A" style={inputStyle} />
                  </Field>
                </FieldRow>
              </div>
            )}

            {/* ── Step 1: Guardian Information ────────────────── */}
            {step === 1 && (
              <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
                <SectionTitle>Guardian Information</SectionTitle>

                <FieldRow>
                  <Field label="Guardian First Name" required>
                    <input type="text" value={guardianFirstName} onChange={e => setGuardianFirstName(e.target.value)} placeholder="e.g. Maria" required style={inputStyle} />
                  </Field>
                  <Field label="Guardian Last Name" required>
                    <input type="text" value={guardianLastName} onChange={e => setGuardianLastName(e.target.value)} placeholder="e.g. Rodriguez" required style={inputStyle} />
                  </Field>
                </FieldRow>

                <Field label="Relationship to Student" required>
                  <select value={relationship} onChange={e => setRelationship(e.target.value)} required style={inputStyle}>
                    <option value="">Select relationship...</option>
                    {RELATIONSHIPS.map(r => <option key={r} value={r}>{r}</option>)}
                  </select>
                </Field>

                <FieldRow>
                  <Field label="Guardian Email" required help="Credentials and password recovery will be sent here.">
                    <input type="email" value={guardianEmail} onChange={e => setGuardianEmail(e.target.value)} placeholder="parent@example.com" required style={inputStyle} />
                  </Field>
                  <Field label="Guardian Phone">
                    <input type="tel" value={guardianPhone} onChange={e => setGuardianPhone(e.target.value)} placeholder="(555) 123-4567" style={inputStyle} />
                  </Field>
                </FieldRow>
              </div>
            )}

            {/* ── Step 2: School Account ──────────────────────── */}
            {step === 2 && (
              <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
                <SectionTitle>School Account</SectionTitle>

                <div style={{
                  background: SURFACE, border: `1px solid ${BORDER}`, borderRadius: 12,
                  padding: 20, display: "flex", flexDirection: "column", gap: 12,
                }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <div style={{
                      width: 8, height: 8, borderRadius: 999,
                      background: "#22c55e",
                    }} />
                    <span style={{ fontSize: 13, fontWeight: 600, color: "#166534" }}>
                      School-managed identity
                    </span>
                  </div>

                  <div style={{ fontSize: 14, color: "#334155", lineHeight: 1.6 }}>
                    <p style={{ margin: "0 0 8px" }}>
                      A <strong>Student ID</strong> and <strong>temporary password</strong> will be
                      auto-generated when you complete registration.
                    </p>
                    <p style={{ margin: "0 0 8px" }}>
                      The student will log in using their Student ID instead of an email address.
                    </p>
                    <p style={{ margin: 0 }}>
                      The student will be required to <strong>change their password</strong> on first login.
                    </p>
                  </div>
                </div>

                <div style={{
                  background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 12,
                  padding: 16, fontSize: 13, color: MUTED, lineHeight: 1.6,
                }}>
                  <strong style={{ color: "#0f172a" }}>Preview</strong>
                  <div style={{ marginTop: 8 }}>
                    Student: <strong style={{ color: "#0f172a" }}>{buildFullName() || "—"}</strong>
                  </div>
                  <div>
                    Grade: <strong style={{ color: "#0f172a" }}>{gradeLevel || "—"}</strong>
                    {section && <> / {section}</>}
                  </div>
                  <div>
                    Guardian: <strong style={{ color: "#0f172a" }}>{buildGuardianName() || "—"}</strong>
                    {relationship && <> ({relationship})</>}
                  </div>
                  <div>
                    Contact: <strong style={{ color: "#0f172a" }}>{guardianEmail || "—"}</strong>
                  </div>
                </div>
              </div>
            )}

            {/* ── Step 3: Enrollment ──────────────────────────── */}
            {step === 3 && (
              <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
                <SectionTitle>Enrollment</SectionTitle>

                <Field label={`Courses (${selectedCourseIds.size} selected)`} required>
                  {loadingCourses ? (
                    <div style={{ fontSize: 13, color: MUTED, padding: 12 }}>Loading courses...</div>
                  ) : courses.length === 0 ? (
                    <div style={{ fontSize: 13, color: MUTED, padding: 12 }}>No courses available for this organization.</div>
                  ) : (
                    <div style={{
                      maxHeight: 240, overflowY: "auto",
                      border: `1px solid ${BORDER}`, borderRadius: 10,
                    }}>
                      {courses.map(c => (
                        <label key={c.id} style={{
                          display: "flex", alignItems: "center", gap: 10,
                          padding: "12px 14px",
                          borderBottom: `1px solid ${BORDER}`,
                          cursor: "pointer", fontSize: 14,
                          background: selectedCourseIds.has(c.id) ? "#eff6ff" : "transparent",
                        }}>
                          <input
                            type="checkbox"
                            checked={selectedCourseIds.has(c.id)}
                            onChange={() => toggleCourse(c.id)}
                            style={{ width: 16, height: 16 }}
                          />
                          <div style={{ display: "flex", flexDirection: "column" }}>
                            <span style={{ fontWeight: 500 }}>{c.title}</span>
                            <span style={{ fontSize: 12, color: MUTED }}>{c.status}</span>
                          </div>
                        </label>
                      ))}
                    </div>
                  )}
                </Field>

                {feedback && (
                  <div style={{
                    padding: "14px 18px", borderRadius: 10, fontSize: 13,
                    whiteSpace: "pre-line", lineHeight: 1.7,
                    background: feedback.ok ? "#dcfce7" : "#fef2f2",
                    color: feedback.ok ? "#166534" : "#7f1d1d",
                    userSelect: feedback.ok ? "all" : "auto",
                    fontFamily: feedback.ok ? "monospace, monospace" : "inherit",
                  }}>
                    {feedback.message}
                  </div>
                )}
              </div>
            )}
          </form>
        </div>

        {/* Footer */}
        <div style={{
          padding: "16px 28px 24px",
          borderTop: `1px solid ${BORDER}`,
          display: "flex", justifyContent: "space-between", alignItems: "center",
        }}>
          <button
            type="button"
            onClick={step === 0 ? onClose : prevStep}
            style={{
              padding: "10px 22px", borderRadius: 10,
              border: `1px solid ${BORDER}`, background: "#fff",
              color: "#334155", fontSize: 14, cursor: "pointer",
            }}
          >
            {step === 0 ? "Cancel" : "Back"}
          </button>

          <div style={{ display: "flex", gap: 10 }}>
            {feedback?.ok && (
              <button type="button" onClick={onClose} style={{
                padding: "10px 22px", borderRadius: 10, border: "none",
                background: PRIMARY, color: "#fff", fontSize: 14, fontWeight: 600, cursor: "pointer",
              }}>
                Done
              </button>
            )}
            {!feedback?.ok && step < STEPS.length - 1 && (
              <button
                type="button"
                onClick={nextStep}
                disabled={
                  (step === 0 && !canAdvanceStep0) ||
                  (step === 1 && !canAdvanceStep1)
                }
                style={{
                  padding: "10px 22px", borderRadius: 10, border: "none",
                  background: PRIMARY, color: "#fff",
                  fontSize: 14, fontWeight: 600,
                  cursor: "pointer",
                  opacity: (
                    (step === 0 && !canAdvanceStep0) ||
                    (step === 1 && !canAdvanceStep1)
                  ) ? 0.5 : 1,
                }}
              >
                Continue
              </button>
            )}
            {!feedback?.ok && step === STEPS.length - 1 && (
              <button
                type="submit"
                form="register-student-form"
                disabled={!canSubmit}
                style={{
                  padding: "10px 22px", borderRadius: 10, border: "none",
                  background: !canSubmit ? MUTED : PRIMARY, color: "#fff",
                  fontSize: 14, fontWeight: 600,
                  cursor: !canSubmit ? "default" : "pointer",
                }}
              >
                {saving ? "Registering..." : "Register Student"}
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
